language: cpp
os:
  - linux
compiler:
  - gcc
before_install:
  - export ROOT=`pwd`
install:
  - cd $ROOT/pqnet && make
  - sudo make install
script:
  - cd $ROOT/pqnet/util/tests && make
  - cd $ROOT/pqnet/core/tests && make
  - cd $ROOT/examples/echo && make -f uselib.mk
  - cd $ROOT/examples/http && make
