name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: |
          make
          sudo make install

      - name: after_install
        run: |
          cd ${GITHUB_WORKSPACE}/pqnet/util/tests && make
          cd ${GITHUB_WORKSPACE}/pqnet/core/tests && make
          cd ${GITHUB_WORKSPACE}/examples/echo && make -f uselib.mk
          cd ${GITHUB_WORKSPACE}/examples/http && make
          cd ${GITHUB_WORKSPACE}/examples/rand64k && make
